/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecon.std;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.ServerSocket;
import java.net.Socket;

public class App {
   
    public static void main(String[] args) {

        System.out.println("..::servidor TCP::..");
        int porta = 1234;

        try(ServerSocket serverSocket= new ServerSocket(porta)){
            while (true) {
                //aguardando por conecções de clientes
                Socket cliente = serverSocket.accept();
               // Thread t = new Thread(new ThreadServidor(cliente));

                //disparando a thead
               // t.start();
                

               // estabelecer fluxos de I/O
                BufferedReader entrada = new BufferedReader(new InputStreamReader(cliente.getInputStream()));
                OutputStreamWriter saida = new OutputStreamWriter(cliente.getOutputStream(),"UTF-8");

           
                String mensagem = entrada.readLine();
                System.out.println("cliente falou: " + mensagem);

                saida.write("Olá, eu sou o Servidor!\n");
                saida.flush();


                
            }

        }catch ( Exception e){
            System.err.println("Erro" + e.toString());
        }


        
    }
}
