/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.nio.Buffer;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
     String servidor =args[0];//"localhost"; //127.0.01;

     int porta = Integer.parseInt(args[1]);

    try (Socket socket = new Socket(servidor, porta)){
        System.out.println("conetado no servidor...");

        // estabelecer fluxos de I/O
        BufferedReader entrada = new BufferedReader(new InputStreamReader(socket.getInputStream()));
        OutputStreamWriter saida = new OutputStreamWriter(socket.getOutputStream(),"UTF-8");

            saida.write("Olá, eu sou o cliente!\n");
            //String resposta = entrada.readLine();
            Scanner teclado = new Scanner(System.in);
            String mensagem = teclado.nextLine();
            System.out.println("servidor falou: " + mensagem);
            saida.flush();

           

     } catch (Exception e) {
        System.err.println("Erro: " + e.toString());
     }
    }
}
