/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.nio.Buffer;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        String servidor = args[0];// "localhost"; //127.0.01;
        int porta = Integer.parseInt(args[1]);

        try (Socket socket = new Socket(servidor, porta)) {
                BufferedReader entrada = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                OutputStreamWriter saida = new OutputStreamWriter(socket.getOutputStream(), "UTF-8");
                Scanner teclado = new Scanner(System.in);
                while (true) {

                    // String resposta = entrada.readLine();

                    String mensagem = teclado.nextLine();
                    saida.write(mensagem + "\n");
                    saida.flush();

                    if (mensagem.equals("fim")) {
                        break;
                    }

                    saida.write("ola. sou o servidor\n");
                    saida.flush();
                    String resposta = entrada.readLine();
                    System.out.println("Resposta do servidor: " + resposta);
                }

            } catch (Exception e) {
                System.err.println("Erro: " + e.toString());
            }

        }

    }
