/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

public class App {
 var outra = Pessoa.newBulder(request).setId(novoId).build();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
